services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  api:
    build: .
    container_name: mlx-api
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  ui:
    build: .
    container_name: mlx-ui
    ports:
      - "8501:8501"
    depends_on:
      - api
    volumes:
      - .:/app
    command: streamlit run streamlit_app.py


volumes:
  redis-data: