services:
  init-redis:
    image: docker.io/tyronen24/ui:latest
    volumes:
      - redis_data:/data
    command: sh -c "cp /app/data/redis_dump.rdb /data/redis_dump.rdb 2>/dev/null || true && chown -R 999:999 /data"

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --dir /data --dbfilename redis_dump.rdb --protected-mode no --loadmodule /opt/redis-stack/lib/redisearch.so
    depends_on:
      - init-redis
    restart: unless-stopped

  app:
    image: docker.io/tyronen24/ui:latest
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: streamlit run ui/webserver.py --server.port=${PORT} --server.address=0.0.0.0
    restart: unless-stopped

volumes:
  redis_data:
