services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/app/data
    command: redis-server --appendonly yes --dir /app/data --dbfilename redis_dump.rdb --protected-mode no --loadmodule /opt/redis-stack/lib/redisearch.so
    restart: unless-stopped

  app:
    image: docker.io/tyronen24/ui:latest
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: streamlit run ui/webserver.py --server.port=${PORT} --server.address=0.0.0.0
    restart: unless-stopped
