[[index]]
name = "pytorch-nightly-cu128"
url = "https://download.pytorch.org/whl/nightly/cu128"

[sources]
torch = [{ index = "pytorch-nightly-cu128" }]
pytorch-triton = [{ index = "pytorch-nightly-cu128" }]
